### ISSUE TITLE
CI workflow for CRI-O HTTP server test failed

### ISSUE THREAD

**Issue by JcJinChen** [second-state/wasmedge-containers-examples#22]
The CI context is 
```
name: CRI-O HTTP server test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      
    - name: Install apt-get packages
      run: |
        sudo ACCEPT_EULA=Y apt-get update
        sudo ACCEPT_EULA=Y apt-get upgrade
        sudo ACCEPT_EULA=Y apt-get install git wget
        
    - name: Install CRI-O and crun
      run: |
        wget -qO- https://raw.githubusercontent.com/second-state/wasmedge-containers-examples/main/crio/install.sh | bash
        
    - name: Run demo in CRI-O
      run: |
        wget -qO- https://raw.githubusercontent.com/second-state/wasmedge-containers-examples/main/crio/http_server/http_server_application.sh | bash
```

According the log of CI, when creating pod, an error appeared,
```
Creating POD ...
time="2022-07-17T00:29:31Z" level=fatal msg="connect: connect endpoint 'unix:///var/run/crio/crio.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded"
```
Similarly, some CIs builded successfully, if you look into the output log, some errors maybe occur.
For example,running `Containerd test` CI, the output log,
```
Creating POD ...
{"msg":"exec container process `/wasi_example_main.wasm`: Exec format error","level":"error","time":"2022-07-18T00:07:38.000967372Z"}
```
